name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    permissions: 
      contents: write
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') }}
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VERSIONBUMPER_ID }}
          private-key: ${{ secrets.VERSIONBUMPER_SECRET }}

      - name: Check out
        uses: actions/checkout@v3
        with:
          token: "${{ steps.app-token.outputs.token }}"
          fetch-depth: 0

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ steps.app-token.outputs.token }}